### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by phanoophong** [mrholek/coreui-free-vue-admin-template#16]
HMR not working

**Comment by rlatkn** [comment]
I just remove this lines from `build/dev-client.js`:
```
hotClient.subscribe(function (event) {
  if (event.action === 'reload') {
    window.location.reload()
  }
})
```
and it start to work normally. I does't know why this lines need

**Comment by xidedix** [comment]
[v1.0.11](https://github.com/mrholek/coreui-free-vue-admin-template/releases/tag/v1.0.11) solves the issue with HMR
