### ISSUE TITLE
Unable to use Bootstrap-Vue DatePicker

### ISSUE THREAD

**Issue by ivandov** [mrholek/coreui-free-vue-admin-template#63]
I am trying to use the bootstrap-vue DatePicker as described here: https://bootstrap-vue.js.org/docs/components/form-input

The `<b-form-input type:"date">` tag does not work as expected.

**Comment by xidedix** [comment]
````vue
<b-form-input type="date">
````

**Comment by ivandov** [comment]
```
<b-form-input id="date" v-model="immunization.date" type="date"></b-form-input>
```
Still not showing up with the datePicker UI components. 
![image](https://user-images.githubusercontent.com/7094613/38042172-3ed18ade-3279-11e8-9593-5080f76ffee5.png)

Does extra JS or CSS need to be added?

**Comment by xidedix** [comment]
Not all browsers support all input types, ex Firefox desktop doesn't support date, datetime, or time. Maybe there is a culprit?

**Comment by ivandov** [comment]
I've checked on both chrome, firefox and safari. All pages load when going to the bootstrap-vue [form-input](https://bootstrap-vue.js.org/docs/components/form-input) page. But, no luck when trying the same through the core-ui templates. 

I started with the "Starter termplate" maybe there's something else I need to import somewhere? Otherwise, I didn't see any working examples on the live preview, no way to verify it's working elsewhere.

**Comment by xidedix** [comment]
Unfortunately cannot reproduce. 
Which version of coreui and bootstrap-vue do you have?

**Comment by ivandov** [comment]
bootstrap-vue@2.0.0-rc.1

Not sure where to get the coreui version. From the starter template that I copied, it shows version 1.0.10 in the package.json. Is there somewhere else that I should be looking? 

Again, maybe [Vue_Starter](https://github.com/mrholek/coreui-free-vue-admin-template/tree/master/Vue_Starter) doesn't have some required imports?

**Comment by xidedix** [comment]
please find maintenance release `v1.0.11` here:  
[https://github.com/mrholek/coreui-free-vue-admin-template/releases/tag/v1.0.11](https://github.com/mrholek/coreui-free-vue-admin-template/releases/tag/v1.0.11)

**Comment by ivandov** [comment]
Is there a documented upgrade process somewhere? Since coreui isn't an npm package, it's a lot of static files, right? What's the best way to go about upgrading?

**Comment by xidedix** [comment]
Hi @ivandov 
Migration from v1.0.10 to v1.0.11 should be straightforward since we changed only:
- scss location 
- imports in App.vue 
- updated webpack scripts
- dependencies in package.json  

Use Vue_Starter v1.0.11 and copy views, routing and _nav from your own project  
hope this helps

BTW there is v2 underway with awaited npm packages for CoreUI components. Stay tuned.
