### ISSUE TITLE
Cant get Table to be responsive

### ISSUE THREAD

**Issue by T0miii** [mrholek/coreui-free-vue-admin-template#65]
I have following problem

![bildschirmfoto vom 2018-03-27 13-34-58](https://user-images.githubusercontent.com/10532141/37965021-e5c1ba78-31c3-11e8-9387-e7f7aa8af332.png)

I have set the responsive class for my table but it sill wont be responsive. Any idea?

**Comment by xidedix** [comment]
wrap your `.table` with `.table-responsive` like this:
````html
<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>
````

see also: [Responsive tables](https://getbootstrap.com/docs/4.0/content/tables/#responsive-tables)

**Comment by T0miii** [comment]
yap, the **-lg** was the problem. Works fine with **table-responsive**, also **-xl**

Thx a lot.
