### ISSUE TITLE
how to start vue after doing npm run build ?

### ISSUE THREAD

**Issue by Davidriquelme** [mrholek/coreui-free-vue-admin-template#69]
I did try with npm run start, but it says starting dev server, 

thanks

**Comment by xidedix** [comment]
built files are meant to be served over an HTTP server

**Comment by Davidriquelme** [comment]
sure, but when deploying on the server, we did the "npm run build", and then for starting the app "npm run start", after this it says "Starting dev server"

![image](https://user-images.githubusercontent.com/12628676/38366323-c68edd7c-38b5-11e8-89d6-407f9cd6b3a1.png)


any thoughts ?

**Comment by Hobbs1210** [comment]
`npm run start` should only be used for dev environment.
all you have to do is point Apache/Nginx/Caddy to the `./dist` folder.
