### ISSUE TITLE
npm ERR! write after end

### ISSUE THREAD

**Issue by aloay** [mrholek/coreui-free-vue-admin-template#78]
each time I try to `$npm install` I get that error!

do you recommend a specific version of NPM or Node?

**Comment by xidedix** [comment]
And, what’s your version of node & npm?

**Comment by aloay** [comment]
@xidedix Thank you for your answer. I installed npm@5 and it worked fine

**Comment by xidedix** [comment]
@aloay Thanks for the follow-up.
I'm closing this since it appears to be solved.
