### ISSUE TITLE
Your support channel for coreui Pro?

### ISSUE THREAD

**Issue by hifall** [mrholek/coreui-free-vue-admin-template#83]
Hi, I just paid for a core UI template of Pro version. However, I am running into an issue and I am unable to find the support channel (email, portal, etc.).

What's your support channel, or I would just post the issue here?

Thanks.

**Comment by Davidriquelme** [comment]
+1

**Comment by hifall** [comment]
Ping

**Comment by xidedix** [comment]
hi @hifall 
For now, please post the issue here.
We are going to provide a separate support channel for CoreUI Pro, shortly after the release of v2.

**Comment by hifall** [comment]
When running: npm run build, I see this error:

ERROR in static/js/vendor.c170bd11af9fe379b1ab.js from UglifyJs
Unexpected token: punc ()) [./node_modules/mini-toastr/mini-toastr.js:12,0][static/js/vendor.c170bd11af9fe379b1ab.js:99884,14]

Any idea?

Version:
CoreUI: Pro
node.js: 8.11.1
npm: 5.6.0
macOS: 10.12

**Comment by xidedix** [comment]
@hifall 
please try to apply a solution from https://github.com/mrholek/coreui-free-vue-admin-template/issues/57

**Comment by hifall** [comment]
No, the solution doesn't work. Same issue.

**Comment by xidedix** [comment]
did you run `npm install` after applying changes to `package.json` ?

**Comment by hifall** [comment]
Oops, my bad.

It all seems ok now.

Thanks!

**Comment by xidedix** [comment]
I'm closing this since it appears to be answered above. Please comment and it will be reopened if you feel the issue has not been resolved.
